source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.0.0'
gem 'dropbox-sdk', require: 'dropbox_sdk'
gem 'haml'
gem 'dotenv-rails'
gem 'high_voltage'
gem 'jquery-rails'
gem 'oauth2'
gem 'pg'
gem 'pry'
gem 'rails', '4.0.3'
gem 'sass-rails', '~> 4.0.0'
gem 'simple_form'
gem 'uglifier', '>= 1.3.0'
